name: mzml2isa
owner: tomnl
description: Parser to get meta information from mzML files and create an ISA-Tab structure
homepage_url: https://github.com/ISA-tools/mzml2isa
long_description: mzml2isa is a Python program that can be used to generate an ISA-Tab structure out of mzML files, providing the backbone of a study which can then be edited with an ISA editing tool (see MetaboLights pre-packaged ISA Creator - http://www.ebi.ac.uk/metabolights/)
remote_repository_url: https://github.com/ISA-tools/mzml2isa
type: unrestricted
categories:
  - "Metabolomics"